#!/usr/bin/env bash

cd /opt/yocto/workspace

# If you'd like to put build/conf under source control, add it as /conf to the project.
# Using TEMPLATECONF doesn't seem to work reliably e.g. with OpenSTLinux.
if [ -d /opt/yocto/conf ]; then
   mkdir -p build
   ln -sf ../../conf build/conf
fi

# TODO source the right env init script; this one's for poky:
source layers/poky/oe-init-build-env build

# Use this instead for STM32MP1:
#export DISTRO=openstlinux-weston
#export MACHINE=stm32mp1
#source layers/meta-st/scripts/envsetup.sh build
